/run/initialize
/control/verbose 1
/tracking/verbose 1
/event/verbose 1
/gps/verbose 2

# Set gamma particle with alpha profile preset and 24 mm distnace
/AVS/Source/SetParticlePreset 0
/AVS/Source/StandDistance     24. mm
/gps/particle gamma
/gps/ene/mono 59.5409 keV

# Set Filename
/B1/Analysis/SetFilename     ./data/preset_gamma_alpha_24mm_1M.root

/AVS/Analysis/RecordPrimaryOnly 1
/AVS/Analysis/SetRecordSet 100

# run 10k particles 
/run/beamOn 1000000